// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async vaultInfo() : Promise<Result<VaultInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArtifacts() : Promise<Result<ArtifactMeta[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_artifacts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readArtifact(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_artifact", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeArtifact(path: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_artifact", { path, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createArtifact(title: string) : Promise<Result<ArtifactMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_artifact", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteArtifact(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_artifact", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy dropped files (absolute paths from the OS drag) into artifacts/.
 */
async importArtifacts(paths: string[]) : Promise<Result<ArtifactMeta[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_artifacts", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchArtifacts(query: string) : Promise<Result<ArtifactMeta[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_artifacts", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run any catalog-declared file import (`IntegrationDef::import`) on a
 * blocking thread with its own Vault handle, reporting progress via
 * "import-progress" events. One command serves every import — a new import
 * is a catalog entry plus a parser, never a new command.
 */
async runImport(integrationId: string, path: string, params: Partial<{ [key in string]: string }>) : Promise<Result<ImportOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_import", { integrationId, path, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild and return the vault manifest: every data folder present, with
 * sources and date ranges — the generic data browser's map.
 */
async vaultManifest() : Promise<Result<Manifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_manifest") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Newest-first raw records from any date-partitioned JSONL directory — the
 * generic "Recent data" read behind every integration card. Jailed by the
 * vault's path resolution; `.trove/` is never readable here.
 */
async readStream(dir: string, limit: number, offset: number) : Promise<Result<StreamPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_stream", { dir, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The dropped file's detected fate: `Detection` serialized (headers, sample
 * rows, format, and the three-outcome `outcome`). No vault I/O — reads only
 * the dropped file at the given absolute OS path.
 */
async normalizerDetect(path: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_detect", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The exact consent payload for an LLM suggestion on this file: `{ payload,
 * request_body }` where `payload` is the [`trove_core::normalizer::SuggestPayload`]
 * (headers + ≤5 sample rows + candidate contract metadata) and `request_body`
 * is the literal Anthropic request body. The UI shows this verbatim before any
 * network call — there is no "always allow".
 */
async normalizerSuggestPayload(path: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_suggest_payload", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the LLM advisor is usable (BYO or baked key), with the reason when
 * not — the gate the suggest control renders disabled against. No network.
 */
async normalizerAdvisorStatus() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_advisor_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run the opt-in cloud advisor after the user has consented, returning a draft
 * [`trove_core::normalizer::Mapping`] that pre-fills the binding form. The
 * payload is rebuilt from the file deterministically (detect → `from_detection`),
 * so it is byte-identical to what `normalizer_suggest_payload` displayed in the
 * consent dialog — what was shown is exactly what is sent. Errors if no key is
 * configured.
 */
async normalizerSuggest(source: string, path: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_suggest", { source, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A dry run of a (possibly-edited) mapping against the dropped file: applies it
 * without writing, returning row counts and a small sample for the validation
 * preview. Pure — no vault I/O beyond reading the dropped file.
 */
async normalizerPreview(path: string, mapping: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_preview", { path, mapping }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Confirm a mapping: persist it under `.trove/mappings/<source>.json`, land the
 * dropped file raw, and project its rows into the domain folders (guid-merged).
 * Progress streams on the "import-progress" event tagged `normalizer`.
 */
async normalizerConfirm(path: string, mapping: JsonValue) : Promise<Result<ImportOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_confirm", { path, mapping }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-project a source from raw after its mapping was edited: delete the
 * projected partitions, rewrite from every raw drop. Idempotent.
 */
async normalizerReproject(source: string) : Promise<Result<ImportOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_reproject", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every stored mapping, in source order (each a serialized `Mapping`).
 */
async normalizerListMappings() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_list_mappings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a mapping and its projected partitions, keeping raw.
 */
async normalizerDeleteMapping(source: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_delete_mapping", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Land a nothing-fits drop raw under `imports/<source>/`, listed in the
 * declined-drops manifest and browsable in the raw viewer. Returns the entry.
 */
async normalizerDecline(source: string, path: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_decline", { source, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The declined-drops manifest: every raw file landed under `imports/`.
 */
async normalizerListDeclined() : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_list_declined") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A page of a raw dropped file rendered as a table (`RawPage` serialized). The
 * path is vault-relative; the authoritative jail (path escapes plus `.trove/`,
 * case-insensitive) lives in core via `Vault::resolve_user`, so it can't be
 * bypassed with a `./` prefix or letter-case variation. Read cost is
 * O(offset + limit), never the whole file.
 */
async normalizerReadRaw(path: string, offset: number, limit: number) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_read_raw", { path, offset, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a bring-your-own Anthropic API key for the advisor (0600, BYO wins over
 * any baked key). Rejects an empty key.
 */
async normalizerSaveKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_save_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget the saved BYO advisor key (a baked key, if any, still applies).
 */
async normalizerDeleteKey() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("normalizer_delete_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listHealthMetrics() : Promise<Result<MetricSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_health_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async healthSeries(metric: string, bucket: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_series", { metric, bucket }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every chartable health metric across all sources (Apple Health import +
 * Oura sync), overlaps merged under one canonical slug.
 */
async healthMetricsUnified() : Promise<Result<UnifiedMetric[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_metrics_unified") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-source series for one canonical metric — sources stay separate so the
 * chart overlays them rather than merging.
 */
async healthSeriesUnified(metric: string, bucket: string) : Promise<Result<SourceSeries[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_series_unified", { metric, bucket }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Latest Oura daily scores (readiness, sleep, activity, stress, resilience,
 * cardio age) for the Overview cards. Empty when Oura has never synced.
 */
async ouraOverview() : Promise<Result<OuraDayScore[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oura_overview") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recent Oura sleep sessions, newest first (naps included, marked by kind).
 */
async ouraSleepNights(limit: number) : Promise<Result<SleepNight[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oura_sleep_nights", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Intraday heart-rate samples in an RFC3339 window, downsampled to at most
 * `max_points`.
 */
async ouraHeartrateRange(start: string, end: string, maxPoints: number) : Promise<Result<HeartratePoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("oura_heartrate_range", { start, end, maxPoints }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The newest workouts and sessions across Apple Health and Oura, merged and
 * source-labeled.
 */
async healthWorkouts(limit: number) : Promise<Result<WorkoutItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_workouts", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-app time plus active/AFK totals over an inclusive date range
 * (YYYY-MM-DD). The in-progress event is added in via `activity_current`.
 */
async activitySummary(from: string, to: string) : Promise<Result<ActivitySummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activity_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activityTimeline(date: string) : Promise<Result<ActivityEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activity_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activityDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activity_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The event currently in progress (not yet written to the log), if any —
 * ours when this app owns collection, otherwise mirrored from the owning
 * process's heartbeat (e.g. the troved daemon).
 */
async activityCurrent() : Promise<ActivityEvent | null> {
    return await TAURI_INVOKE("activity_current");
},
/**
 * Whether Screen Recording is granted (needed for window titles).
 */
async activityPermission() : Promise<boolean> {
    return await TAURI_INVOKE("activity_permission");
},
/**
 * Prompt for Screen Recording (first call only — afterwards macOS requires a
 * trip to System Settings). Returns the resulting permission state.
 */
async requestActivityPermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_activity_permission");
},
async watcherStatus() : Promise<WatcherStatus> {
    return await TAURI_INVOKE("watcher_status");
},
/**
 * Per-app and per-device screen time over an inclusive date range
 * (YYYY-MM-DD). `device` narrows to one device UUID (or "this-mac");
 * `include_idle: false` hides lock screens, StandBy, and watch faces.
 */
async screenTimeSummary(from: string, to: string, device: string | null, includeIdle: boolean) : Promise<Result<ScreenTimeSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("screen_time_summary", { from, to, device, includeIdle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async screenTimeTimeline(date: string, device: string | null, includeIdle: boolean) : Promise<Result<ScreenTimeSession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("screen_time_timeline", { date, device, includeIdle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async screenTimeDaily(from: string, to: string, device: string | null, includeIdle: boolean) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("screen_time_daily", { from, to, device, includeIdle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The device catalog (UUID → kind/label/last-seen); empty until the first
 * Biome sync lands.
 */
async screenTimeDevices() : Promise<Partial<{ [key in string]: DeviceInfo }>> {
    return await TAURI_INVOKE("screen_time_devices");
},
/**
 * Whether this process can read the Biome streams (Full Disk Access).
 * Grants are per-binary — troved needs its own; the hub handles that.
 */
async screenTimePermission() : Promise<boolean> {
    return await TAURI_INVOKE("screen_time_permission");
},
/**
 * Visit count + per-domain counts over an inclusive date range (YYYY-MM-DD).
 */
async browserSummary(from: string, to: string) : Promise<Result<BrowserSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async browserTimeline(date: string) : Promise<Result<BrowserVisit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the browser extension is engaged with *right now* — open spans that
 * haven't closed yet (e.g. a video still playing), read from the live
 * sidecars. Empty when nothing is being watched or no host is connected.
 * Distinct from `browser_timeline`, which only sees closed spans on disk.
 */
async browserLive() : Promise<Result<LiveSpan[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_live") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async browserDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("browser_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cursor/sync metadata — `updated` tells the UI when history last synced.
 * Collection itself runs in the watcher owner loop (app or troved).
 */
async browserSyncInfo() : Promise<BrowserSyncState | null> {
    return await TAURI_INVOKE("browser_sync_info");
},
/**
 * Whether this process can read Safari's History.db (Full Disk Access).
 * There is no programmatic FDA prompt — the UI deep-links to System
 * Settings. Note the grant is per-binary: troved needs its own.
 */
async browserSafariPermission() : Promise<boolean> {
    return await TAURI_INVOKE("browser_safari_permission");
},
/**
 * All ad records that closed on one local day (YYYY-MM-DD). Collection is
 * the extension's opt-in page observer; this only reads what landed.
 */
async adsTimeline(date: string) : Promise<Result<AdRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ads_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Totals plus per-network and per-advertiser aggregates over an inclusive
 * date range (YYYY-MM-DD).
 */
async adsSummary(from: string, to: string) : Promise<Result<AdsSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ads_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ads-seen and ad-viewing-seconds day series over an inclusive range.
 */
async adsDaily(from: string, to: string) : Promise<Result<AdsDaily, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ads_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Play/skip counts, listening time, and top artists over an inclusive
 * date range (YYYY-MM-DD). "Plays" are full plays (Last.fm rule); skips
 * are recorded too but counted separately.
 */
async musicSummary(from: string, to: string) : Promise<Result<MusicSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("music_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async musicTimeline(date: string) : Promise<Result<Play[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("music_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async musicDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("music_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unified media stream (music scrobbles + podcast listens + audible web
 * spans): headline numbers and top artists/shows/sites over an inclusive
 * date range (YYYY-MM-DD).
 */
async mediaSummary(from: string, to: string) : Promise<Result<MediaSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mediaTimeline(date: string) : Promise<Result<MediaItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mediaDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Headline task numbers (open/due/overdue/completed-7d + per-project
 * counts), across every source under tasks/.
 */
async tasksOverview() : Promise<Result<TasksOverview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tasks_overview") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * All open tasks across every source.
 */
async tasksList() : Promise<Result<Task[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tasks_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Completions per day over an inclusive date range (YYYY-MM-DD), from the
 * append-only event stream.
 */
async tasksDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tasks_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync metadata — when each source last synced and any standing error
 * (e.g. an expired token). Collection itself runs in the watcher owner
 * loop (app or troved).
 */
async tasksSyncInfo() : Promise<TasksSyncState | null> {
    return await TAURI_INVOKE("tasks_sync_info");
},
/**
 * Calendar headline numbers over an inclusive date range.
 */
async calendarSummary(from: string, to: string) : Promise<Result<CalendarSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One day's event occurrences, all-day first.
 */
async calendarTimeline(date: string) : Promise<Result<CalendarOccurrence[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scheduled hours per day — the trend series.
 */
async calendarDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recent change-stream entries (reschedules, cancellations, additions).
 */
async calendarChanges(from: string, to: string) : Promise<Result<CalendarChange[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_changes", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync metadata: last pass, backfill state, standing error.
 */
async calendarSyncInfo() : Promise<CalendarSyncState | null> {
    return await TAURI_INVOKE("calendar_sync_info");
},
/**
 * EventKit authorization for this process: "granted" / "denied" /
 * "not-determined", for events and reminders respectively.
 */
async calendarPermission() : Promise<[string, string]> {
    return await TAURI_INVOKE("calendar_permission");
},
/**
 * Fire the Calendar + Reminders TCC prompts (no-ops once decided). Runs off
 * the main thread; blocks up to a minute each so the user can answer.
 * Returns the post-request (granted-events, granted-reminders) pair.
 */
async requestCalendarPermission() : Promise<Result<[boolean, boolean], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_calendar_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Message counts + per-conversation volume over an inclusive date range.
 */
async correspondenceSummary(from: string, to: string) : Promise<Result<CorrespondenceSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correspondence_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async correspondenceTimeline(date: string) : Promise<Result<Message[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correspondence_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async correspondenceDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correspondence_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One page of the Email browser: ranged, newest-first, optionally filtered
 * to one account and/or a substring query, with whole records (body text
 * included) plus the totals and per-account counts the filter chips need.
 */
async emailList(from: string, to: string, account: string | null, query: string | null, limit: number, offset: number) : Promise<Result<EmailPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("email_list", { from, to, account, query, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether this process can read the Messages database (Full Disk Access —
 * same per-binary, deep-link-only grant as Safari history).
 */
async imessagePermission() : Promise<boolean> {
    return await TAURI_INVOKE("imessage_permission");
},
/**
 * Cursor/sync metadata — `updated` tells the UI when messages last synced.
 * Collection itself runs in the watcher owner loop (app or troved).
 */
async imessageSyncInfo() : Promise<IMessageSyncState | null> {
    return await TAURI_INVOKE("imessage_sync_info");
},
/**
 * Call counts, talk time, and per-caller volume over an inclusive range.
 */
async callsSummary(from: string, to: string) : Promise<Result<CallsSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calls_summary", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async callsDaily(from: string, to: string) : Promise<Result<SeriesPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calls_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The newest calls of a range, most recent first — the call log list.
 */
async callsRecent(from: string, to: string, limit: number) : Promise<Result<Message[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calls_recent", { from, to, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether this process can read the call history database (Full Disk
 * Access — same per-binary, deep-link-only grant as Messages).
 */
async callsPermission() : Promise<boolean> {
    return await TAURI_INVOKE("calls_permission");
},
async callsSyncInfo() : Promise<CallsSyncState | null> {
    return await TAURI_INVOKE("calls_sync_info");
},
/**
 * The newest weather observation on file (the "now" card).
 */
async weatherLatest() : Promise<Result<WeatherObservation | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("weather_latest") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One day's hourly observations.
 */
async weatherTimeline(date: string) : Promise<Result<WeatherObservation[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("weather_timeline", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-day aggregates (temps, precipitation, wind, UV) over an inclusive
 * range; uncovered days are omitted.
 */
async weatherDaily(from: string, to: string) : Promise<Result<WeatherDay[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("weather_daily", { from, to }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sync metadata: last pass, last used location, standing error.
 */
async weatherSyncInfo() : Promise<WeatherSyncState | null> {
    return await TAURI_INVOKE("weather_sync_info");
},
/**
 * The manual location, if set.
 */
async weatherLocation() : Promise<WeatherLocation | null> {
    return await TAURI_INVOKE("weather_location");
},
/**
 * Set or clear (`null`) the manual weather location.
 */
async setWeatherLocation(location: WeatherLocation | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_weather_location", { location }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Location Services authorization for this process.
 */
async weatherPermission() : Promise<string> {
    return await TAURI_INVOKE("weather_permission");
},
/**
 * Fire the Location Services TCC prompt (no-op once decided). Runs off the
 * main thread; blocks up to a minute so the user can answer.
 */
async requestWeatherPermission() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_weather_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run one connect method of one registered connection — the generic
 * replacement for the per-service connect commands. Blocking thread: OAuth
 * methods open the browser and wait on the loopback redirect (up to 5
 * minutes). OAuth params: optional `client_id`/`client_secret` (BYO
 * credentials, saved on first use); token-paste params: `token`.
 */
async connectRun(connection: string, method: string, params: Partial<{ [key in string]: string }>) : Promise<Result<ConnectStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_run", { connection, method, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every registered connection's renderable state in one call. Cheap to
 * poll (file reads).
 */
async connectStatusAll() : Promise<Result<ConnectionStatusRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_status_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forget one account of one connection (synced data stays in the vault).
 */
async connectDisconnect(connection: string, key: string) : Promise<Result<ConnectStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_disconnect", { connection, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manual "Sync now" for any integration with a pull hook (network;
 * blocking thread — first pulls can take a while).
 */
async integrationPull(id: string) : Promise<Result<PullOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("integration_pull", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-collection sync progress (watermarks, backfill cursors, standing
 * error). Collection itself runs in the watcher owner loop (app or troved).
 */
async ouraSyncInfo() : Promise<OuraSyncState | null> {
    return await TAURI_INVOKE("oura_sync_info");
},
/**
 * Per-account Gmail sync progress (backfill cursors, history ids, standing
 * errors). Collection itself runs in the watcher owner loop (app or troved).
 */
async gmailSyncInfo() : Promise<GmailSyncState | null> {
    return await TAURI_INVOKE("gmail_sync_info");
},
/**
 * One row per known integration for the hub: catalog metadata + enabled
 * flag + permission preflight + when data last landed. Cheap to poll.
 */
async integrationsStatus() : Promise<Result<IntegrationStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("integrations_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a hub toggle. The collector loops re-read settings every pass, so
 * this takes effect within ~one poll in both the app and troved.
 */
async setIntegrationEnabled(id: string, enabled: boolean) : Promise<Result<IntegrationStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_integration_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Accounts with latest balances, connection state, and sync metadata for
 * the Finance tab and the hub card. Cheap to poll.
 */
async financeOverview() : Promise<Result<FinanceOverview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finance_overview") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Transactions newest-first, all accounts or one, capped at `limit`.
 */
async financeTransactions(account: string | null, limit: number) : Promise<Result<Transaction[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finance_transactions", { account, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * One account row for the Finance tab: registry entry + latest balance.
 */
export type AccountOverview = { id: string; name: string; org: string; currency: string; 
/**
 * Latest snapshot, if any. Decimal strings, never floats.
 */
balance: string | null; available: string | null; 
/**
 * Day of the latest snapshot (YYYY-MM-DD).
 */
balance_date: string | null }
/**
 * One contiguous span of using a single app/window — or being away.
 */
export type ActivityEvent = { 
/**
 * RFC3339 local time, e.g. "2026-06-10T14:03:01-07:00".
 */
start: string; end: string; seconds: number; 
/**
 * Owning app; empty for AFK spans.
 */
app: string; bundle_id?: string; title?: string; afk: boolean }
/**
 * Aggregate of a date range for the Activity view.
 */
export type ActivitySummary = { active_seconds: number; afk_seconds: number; 
/**
 * Apps by active time, descending.
 */
apps: AppUsage[] }
/**
 * One stored ad record (a line in `browser/ads/YYYY-MM-DD.jsonl`).
 */
export type AdRecord = { 
/**
 * Detection time, RFC3339 local.
 */
ts: string; 
/**
 * Close time, RFC3339 local. The file is keyed by this day.
 */
end: string; page_url: string; frame_url: string; landing_url: string; 
/**
 * Serving network (registrable domain of `frame_url`, or the slot
 * family for srcdoc ads — e.g. "google"). "unknown" when neither
 * signal yields anything; honest fields beat guessed ones.
 */
network: string; 
/**
 * Advertiser: registrable domain of `landing_url`, or — when the opt-in
 * `browser-ads-identify` resolver is on and the ad carried a Google
 * transparency link — the human "Paid for by" name (e.g. "Hearts &
 * Science LLC"). Empty if unjoined and unresolved.
 */
advertiser: string; 
/**
 * Google ad-transparency advertiser id (e.g. "AR0405…") when the resolver
 * named `advertiser` — a stable link to adstransparency.google.com.
 */
advertiser_id: string; viewed_secs: number; viewable: boolean; w: number; h: number; source?: string }
/**
 * Per-network or per-advertiser aggregate over a date range.
 */
export type AdUsage = { name: string; count: number; 
/**
 * How many of `count` met the MRC viewability bar.
 */
viewable: number; viewed_secs: number }
/**
 * Two day-series for trends: ads seen and ad-viewing seconds.
 */
export type AdsDaily = { seen: SeriesPoint[]; viewed_secs: SeriesPoint[] }
/**
 * Aggregate of a date range for the (future) Ads view.
 */
export type AdsSummary = { ads: number; viewable: number; viewed_secs: number; 
/**
 * By total viewed time, descending.
 */
networks: AdUsage[]; 
/**
 * Same, advertisers only (records the inspector managed to attribute).
 */
advertisers: AdUsage[] }
/**
 * Per-app time over a date range (active time only).
 */
export type AppUsage = { app: string; seconds: number }
export type ArtifactMeta = { 
/**
 * Path relative to the vault root, e.g. "artifacts/2026-06-10-thoughts.md"
 */
path: string; 
/**
 * First `# ` heading if present, otherwise the filename.
 */
title: string; 
/**
 * Last modified time, seconds since the Unix epoch.
 */
modified: number }
/**
 * One artist's listening over a range.
 */
export type ArtistUsage = { artist: string; 
/**
 * Full plays only (the default chart filter — see [`Play::full_play`]).
 */
plays: number; 
/**
 * Seconds actually played, skips included.
 */
seconds: number }
/**
 * Attachment metadata only — the file itself stays wherever the source app
 * keeps it (copying gigabytes of media into the vault is a later, opt-in
 * decision).
 */
export type AttachmentMeta = { name?: string; mime: string; bytes: number }
/**
 * Aggregate of a date range for the Web view.
 */
export type BrowserSummary = { visits: number; 
/**
 * Domains by visit count, descending.
 */
domains: DomainUsage[] }
/**
 * Incremental-sync cursors, persisted in `.trove/browser-sync.json`.
 * Rebuildable from the JSONL logs (see [`Vault::rebuild_browser_sync`]).
 */
export type BrowserSyncState = { 
/**
 * RFC3339 local time of the last sync pass.
 */
updated: string; 
/**
 * Highest imported `visit_time` (source-native epoch), keyed
 * "browser/profile", e.g. "chrome/Default".
 */
cursors: Partial<{ [key in string]: number }> }
/**
 * One page visit.
 */
export type BrowserVisit = { 
/**
 * RFC3339 local time, e.g. "2026-06-10T14:03:01-07:00".
 */
time: string; url: string; title?: string; 
/**
 * "chrome" (later: "safari", …).
 */
browser: string; profile?: string; 
/**
 * Time on the page per Chrome's `visit_duration`; 0 when unknown.
 */
duration_secs?: number; 
/**
 * Provenance: "history" (imported from the browser's own DB, this
 * module) or "extension" (live capture — richer and authoritative where
 * both exist). Readers resolve overlap in favor of "extension".
 */
source?: string; 
/**
 * Extension rows only: the tab played audio at some point in the span.
 */
audible: boolean; 
/**
 * Extension rows only: seconds spent as the active tab of the focused
 * window (≤ `duration_secs`; the rest is background audible playback).
 */
foreground_secs: number; 
/**
 * Extension rows only: the tab's favicon URL when the browser reported
 * one. Cosmetic (timeline UI); empty for history rows.
 */
favicon: string; 
/**
 * Extension rows only: the page this visit was navigated from (the prior
 * URL for link/form-submit navigations), from `webNavigation`. Empty when
 * the navigation had no in-browser referrer (typed, reload, bookmark) or
 * it couldn't be reconstructed (service worker had restarted).
 */
referrer: string; 
/**
 * Extension rows only: how the navigation happened per `webNavigation`
 * (`link`, `typed`, `reload`, `form_submit`, …). Empty for history rows.
 */
transition: string; 
/**
 * Extension rows only: total open tabs (all windows) when this span
 * opened — a rough "tab clutter" signal. 0/absent when unknown.
 */
tab_count: number }
/**
 * One line of `calendar/changes/YYYY-MM.jsonl`.
 */
export type CalendarChange = { 
/**
 * RFC3339 local time of the sync that observed the change.
 */
ts: string; 
/**
 * "added", "changed", or "removed".
 */
kind: string; id: string; occurrence?: string; title?: string; start?: string; calendar?: string; 
/**
 * Only on `changed`: exactly the fields that drifted.
 */
changes: FieldChange[] }
export type CalendarCount = { calendar: string; account: string; count: number }
/**
 * One event occurrence — a line in `calendar/events/YYYY-MM.jsonl`. Times
 * are RFC3339 local. Only `id` is required to deserialize, so old lines keep
 * parsing as fields are added.
 */
export type CalendarOccurrence = { 
/**
 * EventKit's event identifier — shared by all occurrences of a
 * recurring event, so the diff key is `id` + `occurrence`.
 */
id: string; 
/**
 * The occurrence's original slot (stable across a reschedule of this
 * instance, which is exactly what makes it a usable key).
 */
occurrence?: string; start?: string; end?: string; all_day?: boolean; title?: string; 
/**
 * Calendar name ("Work", "HEALTH", …).
 */
calendar?: string; 
/**
 * Account the calendar syncs from (EKSource title: "iCloud", "Gmail",
 * "dwills@example.com", …).
 */
account?: string; location: string; notes: string; attendees: string[]; 
/**
 * "confirmed" / "tentative" / "canceled" / "" (none reported).
 */
status: string; recurring?: boolean }
/**
 * Headline numbers for the Calendar view.
 */
export type CalendarSummary = { events: number; all_day: number; 
/**
 * Scheduled hours (non-all-day events only).
 */
hours: number; calendars: CalendarCount[] }
/**
 * Persisted in `.trove/calendar-sync.json`.
 */
export type CalendarSyncState = { 
/**
 * RFC3339 local time of the last successful sync.
 */
updated: string; 
/**
 * The one-time history backfill has completed.
 */
backfill_done?: boolean; 
/**
 * Earliest day the backfill reached (YYYY-MM-DD), for display.
 */
backfilled_to: string; error?: string | null }
/**
 * Call volume for one caller over a range, for the Calls view.
 */
export type CallerUsage = { 
/**
 * The other party's handle (number or FaceTime address).
 */
contact: string; 
/**
 * Display name when any record carried a cached contact name.
 */
contact_name: string; calls: number; 
/**
 * Total connected seconds with this caller.
 */
talk_secs: number }
/**
 * Aggregate of a date range for the Calls view.
 */
export type CallsSummary = { calls: number; outgoing: number; 
/**
 * Incoming and connected.
 */
incoming: number; 
/**
 * Incoming, never connected — declined and spam-filtered included.
 */
missed: number; 
/**
 * Total connected seconds across the range.
 */
talk_secs: number; 
/**
 * Callers by call count, descending.
 */
callers: CallerUsage[] }
/**
 * Incremental-sync state, persisted in `.trove/calls-sync.json`.
 * Rebuildable from the JSONL logs (see [`Vault::rebuild_calls_sync`]).
 */
export type CallsSyncState = { 
/**
 * RFC3339 local time of the last sync pass.
 */
updated: string; 
/**
 * Highest imported `ZCALLRECORD.Z_PK`.
 */
cursor: number }
/**
 * Message volume for one conversation over a range.
 */
export type ChatUsage = { chat: string; 
/**
 * Display name when any record carried one.
 */
chat_name: string; source: string; messages: number; sent: number }
/**
 * What the hub needs to render one connect method, straight off the def.
 */
export type ConnectMethodInfo = { kind: "oauth"; multi_account: boolean } | { kind: "token-paste"; label: string; help: string; placeholder: string }
/**
 * A connection's whole state, off [`ConnectionDef::status`].
 */
export type ConnectStatus = { 
/**
 * App credentials saved or compiled in — connecting is just a login.
 * `false` = the hub shows the bring-your-own-credentials form first.
 */
configured: boolean; accounts: ConnectedAccount[] }
/**
 * Generic envelope for one connected account/login — what any service's
 * status hook maps its typed account into (the `MediaItem` trick). Never
 * carries the token itself. No `skip_serializing_if` here on purpose: the
 * generated TS bindings stay honest.
 */
export type ConnectedAccount = { 
/**
 * Disconnect key: account sub for multi-account services, the service
 * id otherwise.
 */
key: string; 
/**
 * What the row shows: email or display name.
 */
label: string; 
/**
 * RFC3339 local time of the connect, when known.
 */
connected_at: string | null; 
/**
 * Access-token expiry, epoch seconds (None = unknown/none). For
 * no-refresh services this is when a reconnect will be needed.
 */
expires_at: number | null; 
/**
 * Re-login required (refresh failed / token expired). The account is
 * kept and flagged, never silently dropped.
 */
needs_reconnect: boolean; 
/**
 * Service-specific details worth showing, named.
 */
extra: Partial<{ [key in string]: string }> }
/**
 * One row of the generic `connect_status_all` command: everything the hub
 * needs to render one connection's card section.
 */
export type ConnectionStatusRow = { id: string; display_name: string; methods: ConnectMethodInfo[]; auto_pull: string[]; setup: string[]; status: ConnectStatus }
/**
 * Aggregate of a date range for the Correspondence view.
 */
export type CorrespondenceSummary = { 
/**
 * kind == "message" only — reactions and group events are stored but not
 * counted as conversation volume.
 */
messages: number; sent: number; received: number; 
/**
 * Messages per source ("imessage" → n), descending.
 */
sources: Partial<{ [key in string]: number }>; 
/**
 * Conversations by message count, descending.
 */
chats: ChatUsage[] }
/**
 * One device in the `screen-time/devices.json` catalog.
 */
export type DeviceInfo = { kind: string; 
/**
 * Vault subdirectory name, e.g. "iphone-58a03ead". Fixed once chosen so
 * file paths stay stable even if inference improves later.
 */
label: string; 
/**
 * RFC3339 local time of the newest event seen from this device.
 */
last_seen?: string; 
/**
 * Raw `DevicePeer.platform` from Biome's sync.db, when known.
 */
platform?: number | null; 
/**
 * OS build string from sync.db (e.g. "25F80"), when known.
 */
model: string }
/**
 * Visits per domain over a date range.
 */
export type DomainUsage = { domain: string; visits: number }
/**
 * One page of the email browser: the requested slice plus the counts the
 * view needs to render filters without a second scan.
 */
export type EmailPage = { 
/**
 * Messages matching the filters (range/account/query), newest first,
 * after `offset`/`limit` — full records, body text included.
 */
messages: Message[]; 
/**
 * Total matches before pagination (drives "N emails" + Load more).
 */
total: number; 
/**
 * Matches per account address (the record's `service`) over the same
 * filters minus the account filter itself — so the account chips keep
 * their counts while one account is selected.
 */
accounts: Partial<{ [key in string]: number }> }
/**
 * One drifted field on a `changed` event.
 */
export type FieldChange = { 
/**
 * "play_count", "rating", or "last_played".
 */
field: string; old: JsonValue; new: JsonValue }
/**
 * Everything the Finance tab and hub card need in one read.
 */
export type FinanceOverview = { 
/**
 * A SimpleFIN credential is present in the Keychain.
 */
connected: boolean; state: FinanceSyncState | null; accounts: AccountOverview[] }
/**
 * Sync metadata for the hub and Finance tab (`.trove/sync/finance-state.json`).
 */
export type FinanceSyncState = { 
/**
 * RFC3339 local time of the last successful sync; "" if never.
 */
updated?: string; 
/**
 * Unix epoch of the last successful sync — drives the next window.
 */
last_epoch?: number | null; 
/**
 * Standing failure (auth, network) or Bridge-reported connection
 * warnings ("Chase may need attention"), for the UI.
 */
error?: string | null; accounts?: number; new_transactions?: number }
/**
 * Per-account sync progress, persisted in `.trove/gmail-sync.json` (keyed by
 * Google `sub`). Deleting an account's entry re-runs its backfill.
 */
export type GmailAccountState = { 
/**
 * Display address (for the index / UI; the map key is the `sub`).
 */
email?: string; 
/**
 * The incremental cursor: Gmail mailbox `historyId`. Captured from the
 * profile before backfill begins, then advanced by each `history.list`.
 */
history_id?: string | null; 
/**
 * `messages.list` resume token for an in-progress backfill.
 */
backfill_page_token?: string | null; 
/**
 * The baseline `historyId` has been captured and backfill has begun.
 */
backfill_started?: boolean; 
/**
 * Backfill has walked the whole mailbox; incremental now drives updates.
 */
backfill_done?: boolean; 
/**
 * Total messages ever written for this account (drives index.md).
 */
messages?: number; 
/**
 * Why this account's last pass failed, for the UI.
 */
error?: string | null }
/**
 * The whole Gmail sync state.
 */
export type GmailSyncState = { 
/**
 * RFC3339 local time of the last sync attempt.
 */
updated: string; 
/**
 * Per-account progress, keyed by Google `sub`.
 */
accounts: Partial<{ [key in string]: GmailAccountState }> }
/**
 * One intraday heart-rate sample (Oura records ~every 5 minutes).
 */
export type HeartratePoint = { 
/**
 * RFC3339, as recorded.
 */
ts: string; bpm: number }
/**
 * Incremental-sync state, persisted in `.trove/imessage-sync.json`.
 * Rebuildable from the JSONL logs (see [`Vault::rebuild_imessage_sync`]).
 */
export type IMessageSyncState = { 
/**
 * RFC3339 local time of the last sync pass.
 */
updated: string; 
/**
 * Highest imported `message.ROWID`.
 */
cursor: number }
/**
 * The serializable face of an [`ImportSpec`] (what the hub needs to render
 * the picker and param fields), carried on `IntegrationStatus`.
 */
export type ImportInfo = { accepts: string[]; params: ImportParam[] }
/**
 * Generic outcome of one import, rendered by the hub: a human headline
 * plus named counts. The importer's typed stats stay internal.
 */
export type ImportOutcome = { 
/**
 * e.g. "1,204 messages imported, 320 duplicates skipped".
 */
headline: string; counts: Partial<{ [key in string]: number }> }
/**
 * One user-supplied field of an import (account address, handle, …),
 * rendered by the hub as a text input — so a new import ships its whole
 * setup UI from the catalog, with zero frontend code.
 */
export type ImportParam = { 
/**
 * Key in the params map handed to [`ImportSpec::run`].
 */
key: string; label: string; placeholder: string; required: boolean }
/**
 * How an integration runs — drives which controls the hub shows.
 */
export type IntegrationKind = 
/**
 * Always-on capture inside the watcher loop (or a host process); the
 * stream only exists while a collector runs.
 */
"live" | 
/**
 * Periodic read of another local app's own store (copy-then-read).
 */
"local-sync" | 
/**
 * Periodic pull from a cloud API (OAuth / token).
 */
"cloud-sync" | 
/**
 * User-triggered file import; nothing runs in the background.
 */
"import"
/**
 * What the hub renders: one row per catalog entry plus live state.
 */
export type IntegrationStatus = { id: string; name: string; kind: IntegrationKind; description: string; 
/**
 * Taxonomy domain token the hub groups by (see [`Integration::domain`]).
 */
domain: string; vault_path: string; toggleable: boolean; 
/**
 * Catalogued but not built yet ([`crate::registry::Behavior::NotWired`]):
 * the hub shows a "planned" badge and no controls — nothing runs until
 * a collector is wired.
 */
planned: boolean; setup: string[]; caveats: string; enabled: boolean; 
/**
 * Why this source can't be built, for catalogued-but-unavailable
 * entries ([`crate::registry::Behavior::Unavailable`]). `Some` = the
 * hub greys the card, hides every control, and shows this copy.
 */
unavailable_reason: string | null; 
/**
 * Permission this integration depends on, if any.
 */
permission: PermissionInfo | null; 
/**
 * When data last landed (or last sync pass ran): RFC3339 local time or
 * a bare date, whichever the cheap probe yields. `None` = no data yet.
 */
last_data: string | null; 
/**
 * Present for file imports: what the hub's generic import box needs
 * (accepted extensions + param fields), straight off the def.
 */
import: ImportInfo | null; 
/**
 * The connection (login) this integration needs, by id — the hub joins
 * it against `connect_status_all`. `None` = no login.
 */
connection: string | null; 
/**
 * Has a manual "Sync now" hook (the generic `integration_pull`).
 */
pullable: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * One currently-open span, surfaced for live "watching now" display. This is
 * ephemeral UI state derived from [`TabTracker`]'s in-memory open spans — it
 * is *never* written to the day JSONL (which records closed spans only). See
 * [`TabTracker::live`] and [`crate::vault::Vault::write_browser_live`].
 */
export type LiveSpan = { url: string; title?: string; favicon: string; 
/**
 * Engaged wall-seconds so far (span start → now).
 */
duration_secs: number; 
/**
 * Of which, seconds spent as the focused-active tab.
 */
foreground_secs?: number; 
/**
 * Played audio at some point in the span.
 */
audible?: boolean; 
/**
 * Is this the focused-active tab right now (vs. background audio only)?
 */
foreground?: boolean }
/**
 * A rebuildable index of what's in the vault, for analyzers, LLMs, and the
 * generic data browser to orient cheaply. Never authoritative — readers
 * scan files, the manifest only points.
 */
export type Manifest = { 
/**
 * RFC3339 local time of the last rebuild.
 */
updated: string; domains: ManifestDomain[] }
/**
 * One data folder: a named contract, or a best-effort entry for any folder
 * of date-named JSONL a collector invented (M6 sources appear without
 * registration).
 */
export type ManifestDomain = { 
/**
 * The contract id, or the folder path for unregistered streams.
 */
domain: string; layout: string; 
/**
 * "event-stream" | "snapshot-plus-events" | "snapshot" | "metric-series".
 */
kind: string; 
/**
 * Source folders present (empty for single-stream folders).
 */
sources: string[]; 
/**
 * Oldest / newest partition key present (YYYY-MM or YYYY-MM-DD).
 */
first?: string | null; last?: string | null; 
/**
 * Partition files present (cheap; line counts are not maintained).
 */
files: number; 
/**
 * Spec page for named contracts, "" for discovered folders.
 */
spec: string }
/**
 * One media play in the unified stream, normalized across sources.
 */
export type MediaItem = { 
/**
 * RFC3339 local time the play happened (started, for spans).
 */
ts: string; 
/**
 * Provenance: which collector produced this — "music", "podcasts",
 * "web", or "iphone-nowplaying" (later: "spotify", …).
 */
source: string; 
/**
 * Content type: "music", "podcast", "audiobook", "video", or "other".
 * Deterministic for the dedicated collectors; classified from the app +
 * metadata for Now Playing (see [`classify_nowplaying`]). This is the
 * axis the Media UI filters on.
 */
category: string; 
/**
 * Device label the play came from — "iPhone"/"iPad" (per-device, e.g.
 * "iPad (2)") for Now Playing sessions, "Mac" for the local scrobbler and
 * browser extension, "" when unknown (the Podcasts snapshot is
 * iCloud-synced and carries no device). The Media UI's second filter axis
 * and the value is the filter key itself.
 */
device: string; 
/**
 * "play" (a real listen/watch) or "partial" (music skip, podcast
 * progress without completion).
 */
kind: string; 
/**
 * Track / episode / page title.
 */
title: string; 
/**
 * Artist / show / domain — the grouping key for top charts.
 */
subtitle: string; 
/**
 * Album / "" / full URL.
 */
detail: string; 
/**
 * Seconds actually played — measured for music and web, a
 * playhead-delta estimate for podcasts; 0 when unknown.
 */
seconds: number; favicon: string; 
/**
 * Source-unique id for re-runnable imports (the media-plays write
 * contract); empty for the read-time arms.
 */
guid: string; 
/**
 * Source-specific fields the normalized shape has no column for —
 * full fidelity at write time, never dropped.
 */
extra: Partial<{ [key in string]: JsonValue }> }
/**
 * Headline numbers for the unified stream over a date range.
 */
export type MediaSummary = { 
/**
 * Full plays across all sources.
 */
plays: number; 
/**
 * Partial plays (music skips, podcast progress).
 */
partials: number; 
/**
 * Seconds played: measured for music + web, estimated for podcasts.
 */
seconds: number; 
/**
 * Items (plays + partials) per source.
 */
sources: Partial<{ [key in string]: number }>; 
/**
 * Items (plays + partials) per device kind ("iphone"/"ipad"/"mac"),
 * the unknown-device "" bucket omitted — the device filter's chips.
 */
devices: Partial<{ [key in string]: number }>; 
/**
 * Artists/shows/sites by plays then seconds, descending.
 */
top: MediaUsage[] }
/**
 * One artist/show/site's listening over a range.
 */
export type MediaUsage = { 
/**
 * The [`MediaItem::subtitle`] grouping key.
 */
name: string; 
/**
 * Content type this row belongs to (the filter axis): "music",
 * "podcast", "audiobook", "video", or "other".
 */
category: string; 
/**
 * Device label this row's plays came from ("iPhone"/"iPad"/"Mac"/""), so
 * the top chart filters by device too.
 */
device: string; 
/**
 * Full plays only (partials excluded, same rule as the music charts).
 */
plays: number; 
/**
 * Seconds played, partials included (podcast seconds are estimates).
 */
seconds: number }
/**
 * One message in any conversation medium.
 */
export type Message = { 
/**
 * RFC3339 local time the message was sent/received.
 */
ts: string; 
/**
 * "imessage" | "email" | "slack" | …
 */
source: string; 
/**
 * Conversation key within the source: the other party's handle or the
 * group chat identifier (iMessage), the thread subject (email), the
 * channel name (Slack).
 */
chat?: string; 
/**
 * Human display name for the chat when the source has one (group chat
 * names, channel topics). Empty for plain 1:1 threads.
 */
chat_name: string; 
/**
 * Canonical address of the author: phone/email handle, email address,
 * Slack username. Empty when `from_me` (the vault owner is implicit).
 */
sender?: string; 
/**
 * Display name for the sender when the source carries one.
 */
sender_name: string; from_me?: boolean; 
/**
 * "message" (default), "reaction" (tapbacks etc.), "event" (group
 * renames, member changes), or "call" (phone/FaceTime).
 */
kind?: string; text?: string; 
/**
 * Connected seconds for kind "call" (0 = missed/unanswered).
 */
duration_secs: number; 
/**
 * Explicit recipients, when the medium has them (email to/cc).
 */
to: string[]; subject: string; 
/**
 * Transport detail: "iMessage"/"SMS"/"RCS", the email account address,
 * the Slack workspace.
 */
service: string; attachments: AttachmentMeta[]; 
/**
 * Reaction name for kind "reaction": "loved", "liked", "disliked",
 * "laughed", "emphasized", "questioned", "emoji", or "removed-…".
 */
reaction: string; 
/**
 * Source-native id of the message this reacts or replies to.
 */
reply_to: string; 
/**
 * Source-native labels/folders the message carries: Gmail system labels
 * (`INBOX`, `SENT`, `IMPORTANT`, `CATEGORY_PROMOTIONS`, …) and user
 * labels. A read-time filter — "human correspondence" is `INBOX`/`SENT`
 * minus the `CATEGORY_*` buckets. Empty for sources without labels.
 */
labels: string[]; 
/**
 * Source-unique id (iMessage guid, email Message-ID, Slack channel/ts) —
 * the dedupe key within a source.
 */
guid: string; 
/**
 * Source-native monotonic id where one exists (iMessage ROWID); drives
 * incremental cursors and their rebuild from these files.
 */
rowid: number }
/**
 * How daily values combine into coarser (week/month) buckets.
 */
export type MetricKind = 
/**
 * Daily totals; coarser buckets sum the days (steps, energy).
 */
"sum" | 
/**
 * Point measurements; coarser buckets take the weighted average (heart rate).
 */
"avg" | 
/**
 * Daily totals; coarser buckets average the days (sleep hours per night).
 */
"sum-then-avg"
export type MetricSummary = { 
/**
 * Folder name under health/, e.g. "heart-rate".
 */
slug: string; name: string; unit: string; kind: MetricKind; records: number; 
/**
 * First/last day with data, YYYY-MM-DD.
 */
first_date: string; last_date: string }
/**
 * Headline listening numbers over a date range.
 */
export type MusicSummary = { 
/**
 * Full plays (Last.fm rule).
 */
plays: number; 
/**
 * Recorded partial plays — bailed before the full-play bar.
 */
skips: number; 
/**
 * Seconds actually played across all rows, pauses excluded.
 */
seconds_played: number; 
/**
 * Artists by full plays, descending.
 */
artists: ArtistUsage[] }
/**
 * Per-collection sync progress, persisted in `.trove/oura-sync.json`.
 */
export type OuraCollectionState = { 
/**
 * Newest day (YYYY-MM-DD) synced through; incremental passes resume
 * a few days behind it (recalculation overlap).
 */
watermark: string | null; 
/**
 * Earliest window-start the backfill has walked back to; the next
 * backfill window ends here. Deleting the sync file re-walks history.
 */
backfill_cursor: string | null; backfill_done: boolean; 
/**
 * Empty windows seen in a row — `BACKFILL_EMPTY_STOP` of them ends
 * the walk.
 */
empty_windows?: number; 
/**
 * Total records ever written for this collection (drives index.md).
 */
records: number }
/**
 * Latest value of one Oura daily score, for the Overview cards.
 */
export type OuraDayScore = { slug: string; name: string; day: string; 
/**
 * Numeric score/value; None for purely categorical scores.
 */
value?: number | null; 
/**
 * Categorical reading (resilience level, stress day summary).
 */
label?: string | null }
export type OuraSyncState = { 
/**
 * RFC3339 local time of the last sync attempt.
 */
updated: string; 
/**
 * Why the last attempt failed (expired token, rate limit), for the UI.
 */
error?: string | null; collections: Partial<{ [key in string]: OuraCollectionState }> }
/**
 * macOS permission an integration depends on, with its preflight result.
 */
export type PermissionInfo = { 
/**
 * "screen-recording" | "full-disk-access" | "media-library"
 */
kind: string; 
/**
 * Preflight from *this* process — `None` when it can't be checked
 * cheaply (Media Library only fails at read time). Note the grant is
 * per-binary: troved needs its own, this reflects the app.
 */
granted: boolean | null; 
/**
 * `false` = the integration works without it, just with less detail
 * (e.g. activity runs app-level without Screen Recording).
 */
required: boolean }
/**
 * One completed play (full listen or skip) — a line in
 * `music/plays/YYYY-MM-DD.jsonl`.
 */
export type Play = { 
/**
 * RFC3339 local time playback of this track began.
 */
start: string; 
/**
 * RFC3339 local time playback last ran (pauses after this are not included).
 */
end: string; 
/**
 * Seconds actually spent playing — pauses excluded.
 */
seconds_played: number; track: string; artist: string; album: string; genre?: string; duration_secs?: number | null; persistent_id?: string; 
/**
 * Did this count as actually listening (Last.fm rule, see
 * [`ScrobbleConfig`])? False = a skip. The default read-time filter;
 * recomputable from `seconds_played`/`duration_secs` if the rule changes.
 */
full_play?: boolean }
/**
 * Per-project open count for the overview.
 */
export type ProjectCount = { source: string; project: string; open: number }
/**
 * Generic outcome of one manual pull ("Sync now"), mirroring
 * [`ImportOutcome`]: a human headline plus named counts. The service's
 * typed stats stay internal.
 */
export type PullOutcome = { headline: string; counts: Partial<{ [key in string]: number }> }
/**
 * Per-app usage over a range.
 */
export type ScreenTimeAppUsage = { app: string; bundle_id: string; seconds: number }
/**
 * Per-device usage over a range.
 */
export type ScreenTimeDeviceUsage = { device: string; kind: string; label: string; seconds: number }
/**
 * One contiguous foreground session of one app on one device.
 */
export type ScreenTimeSession = { 
/**
 * RFC3339 local time.
 */
start: string; end: string; seconds: number; 
/**
 * Friendly app name derived from the bundle id.
 */
app: string; bundle_id: string; 
/**
 * Biome device UUID ("this-mac" for the local-stream backup arm).
 */
device: string; 
/**
 * "iphone" | "ipad" | "watch" | "mac" | "this-mac" | "ios" | "unknown".
 */
device_kind: string; 
/**
 * Provenance: always "biome-infocus" here.
 */
source?: string }
/**
 * Aggregate of a date range for the Screen Time view.
 */
export type ScreenTimeSummary = { total_seconds: number; 
/**
 * Apps by time, descending.
 */
apps: ScreenTimeAppUsage[]; 
/**
 * Devices by time, descending.
 */
devices: ScreenTimeDeviceUsage[] }
export type SeriesPoint = { 
/**
 * Bucket start day, YYYY-MM-DD.
 */
date: string; value: number }
/**
 * One night from Oura's `sleep` sessions. Durations in hours.
 */
export type SleepNight = { day: string; bedtime_start: string; bedtime_end: string; 
/**
 * "long_sleep" | "late_nap" | "sleep" | "rest".
 */
kind: string; total_hours: number; deep_hours: number; rem_hours: number; light_hours: number; awake_hours: number; efficiency?: number | null; latency_min?: number | null; average_hrv?: number | null; lowest_heart_rate?: number | null; average_heart_rate?: number | null; respiratory_rate?: number | null }
/**
 * One source's series for a metric — charted side by side, never merged.
 */
export type SourceSeries = { source: string; points: SeriesPoint[] }
/**
 * Per-source sync status, persisted in `.trove/tasks-sync.json`.
 */
export type SourceSync = { 
/**
 * RFC3339 local time of the last successful sync of this source.
 */
updated: string; 
/**
 * Why the last attempt failed (e.g. an expired token), for the UI.
 */
error?: string | null }
/**
 * One page of a generic stream read, newest records first.
 */
export type StreamPage = { records: JsonValue[]; 
/**
 * Partition keys present, newest first.
 */
partitions: string[] }
export type Subtask = { title: string; done?: boolean; completed?: string | null }
/**
 * One task, in the normalized cross-source schema. Times are RFC3339 local.
 */
export type Task = { 
/**
 * Which collector wrote this ("ticktick", "reminders", …).
 */
source: string; 
/**
 * Source-native task id.
 */
id: string; title: string; 
/**
 * Project / list name, verbatim from the source (may carry emoji).
 */
project?: string; 
/**
 * Free-form notes/body.
 */
notes?: string; 
/**
 * "open" or "done" (snapshots normally hold only open tasks).
 */
status?: string; 
/**
 * TickTick scale: 0 none, 1 low, 3 medium, 5 high. Other sources map in.
 */
priority?: number; due?: string | null; start?: string | null; all_day?: boolean; 
/**
 * Raw RRULE when the task repeats.
 */
recurrence?: string | null; tags: string[]; subtasks: Subtask[]; created?: string | null; modified?: string | null; 
/**
 * For a recurring task this is the last instance completion — the diff
 * watches it advance to log instance completions.
 */
completed?: string | null; 
/**
 * Everything source-specific the normalized fields don't carry
 * (TickTick: projectId, columnId, etag, sortOrder, timeZone, …).
 */
extra: Partial<{ [key in string]: JsonValue }> }
/**
 * Aggregate for the Tasks view, across all sources.
 */
export type TasksOverview = { open: number; due_today: number; overdue: number; 
/**
 * Completions logged in the last 7 days (event stream).
 */
completed_7d: number; 
/**
 * Projects with open tasks, descending by count.
 */
projects: ProjectCount[] }
export type TasksSyncState = { 
/**
 * RFC3339 local time of the last sync attempt, any source.
 */
updated: string; sources: Partial<{ [key in string]: SourceSync }> }
/**
 * The canonical transaction record (`finance/transactions/<account>/<year>.jsonl`).
 */
export type Transaction = { 
/**
 * Stable per source: the backend's own id (SimpleFIN) or a synthesized
 * content hash (file imports, phase 2).
 */
id: string; 
/**
 * Vault account id (the `Account.id` slug).
 */
account: string; 
/**
 * YYYY-MM-DD local — decides which year file the record lives in.
 */
posted: string; 
/**
 * When the purchase actually happened, if the source distinguishes it.
 */
transacted?: string | null; 
/**
 * Signed decimal string ("-42.17"), never a float.
 */
amount: string; currency?: string; description: string; 
/**
 * Normalized later by the categorization pass (phase 3); sources that
 * already provide one (SimpleFIN sometimes does) pass it through.
 */
payee?: string | null; 
/**
 * Null until the categorization phase (or a Copilot import) fills it.
 */
category?: string | null; 
/**
 * Pending rows are ephemeral: each sync replaces the account's pending
 * set (pending→posted often changes the id).
 */
pending?: boolean; 
/**
 * "simplefin" | "csv-import" | "copilot" | "amazon" | …
 */
source: string; 
/**
 * Source-specific passthrough (memo, raw fields, merge audit trail).
 */
extra: Partial<{ [key in string]: JsonValue }> }
/**
 * A canonical metric with every source that reports it.
 */
export type UnifiedMetric = { slug: string; name: string; unit: string; kind: MetricKind; 
/**
 * Methodology caveat shown under the chart (e.g. Apple HRV is SDNN,
 * Oura's is rMSSD — comparable trend, different absolute numbers).
 */
note?: string | null; sources: UnifiedSourceInfo[] }
/**
 * One source's contribution to a unified metric.
 */
export type UnifiedSourceInfo = { source: string; records: number; first_date: string; last_date: string }
export type VaultInfo = { root: string }
export type WatcherStatus = { 
/**
 * Who is collecting right now: "app", "daemon", or "none".
 */
collector: string; 
/**
 * Whether the troved launch agent plist is installed.
 */
daemon_installed: boolean }
/**
 * Per-day aggregate computed at read time from the hourly observations.
 * "Opinions at read time": the JSONL keeps every field, this is just what
 * the chart wants.
 */
export type WeatherDay = { 
/**
 * YYYY-MM-DD.
 */
date: string; temp_min: number; temp_max: number; temp_avg: number; precip_mm: number; wind_max_kmh: number; uv_max: number | null; 
/**
 * How many hourly observations the day has (24 = full coverage).
 */
observations: number }
/**
 * A user-set location, the no-permission path. `.trove/weather-location.json`.
 */
export type WeatherLocation = { lat: number; lon: number; place?: string }
/**
 * One recorded observation. Everything the API's `current` block returns,
 * plus the (rounded) coordinates it was asked about. Only `ts` is required
 * to deserialize so old lines keep parsing as fields evolve.
 */
export type WeatherObservation = { 
/**
 * RFC3339 local time, stamped at fetch.
 */
ts: string; lat?: number; lon?: number; 
/**
 * Human label for the location when one is known (manual config).
 */
place: string; temp_c?: number; apparent_c?: number; humidity_pct?: number; dew_point_c?: number; precip_mm?: number; rain_mm?: number; showers_mm?: number; snowfall_cm?: number; 
/**
 * WMO weather interpretation code (0 clear … 99 thunderstorm w/ hail).
 */
weather_code?: number; cloud_pct?: number; 
/**
 * Mean-sea-level pressure.
 */
pressure_hpa?: number; wind_kmh?: number; wind_dir_deg?: number; wind_gusts_kmh?: number; uv_index?: number | null; is_day?: boolean; source?: string }
/**
 * Collector state: written every pass that does something, surfaced on the
 * Weather tab. Rebuildable — losing it costs at most one duplicate-hour gap.
 */
export type WeatherSyncState = { 
/**
 * RFC3339 local time of the last pass that got as far as a decision.
 */
updated?: string; 
/**
 * `ts` of the newest appended observation.
 */
last_observation?: string; 
/**
 * The location last used successfully (ladder rung 3).
 */
lat?: number; lon?: number; place?: string; 
/**
 * Non-empty while the collector is stuck (no location, network error) —
 * the UI banner reads this.
 */
error: string }
/**
 * One workout or session, from either source.
 */
export type WorkoutItem = { source: string; day: string; start: string; end: string; 
/**
 * Activity type ("Running", "walking", "meditation", …).
 */
activity: string; 
/**
 * "workout" | "session" (Oura sessions: meditation, naps, breathing).
 */
kind: string; duration_min?: number | null; calories?: number | null; distance_km?: number | null; intensity?: string | null; label?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
